ALTER TABLE datasource COMMENT = '数据源主表';

ALTER TABLE datasource
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT '数据源显示名称',
    MODIFY COLUMN description VARCHAR(500) NULL COMMENT '数据源描述',
    MODIFY COLUMN db_type VARCHAR(20) NOT NULL DEFAULT 'MYSQL' COMMENT '数据库类型，MVP 仅支持 MYSQL',
    MODIFY COLUMN host VARCHAR(255) NOT NULL COMMENT '数据库主机地址',
    MODIFY COLUMN port INT NOT NULL DEFAULT 3306 COMMENT '数据库端口',
    MODIFY COLUMN database_name VARCHAR(100) NOT NULL COMMENT '数据库名称',
    MODIFY COLUMN charset VARCHAR(20) NOT NULL DEFAULT 'utf8mb4' COMMENT '连接字符集',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '启用状态：1=启用，0=禁用',
    MODIFY COLUMN health_status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' COMMENT '健康状态：UNKNOWN/HEALTHY/UNHEALTHY',
    MODIFY COLUMN creator_id BIGINT NOT NULL COMMENT '创建人用户 ID',
    MODIFY COLUMN deleted BIGINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0=未删除，删除后写入本记录 ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE datasource_secret COMMENT = '数据源密钥表';

ALTER TABLE datasource_secret
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN datasource_id BIGINT NOT NULL COMMENT '关联数据源 ID',
    MODIFY COLUMN username VARCHAR(100) NOT NULL COMMENT '数据库只读用户名',
    MODIFY COLUMN encrypted_password VARCHAR(500) NOT NULL COMMENT 'AES-256-GCM 加密后的数据库密码',
    MODIFY COLUMN encrypt_version INT NOT NULL DEFAULT 1 COMMENT '加密版本号',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE datasource_access COMMENT = '数据源访问授权表';

ALTER TABLE datasource_access
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN datasource_id BIGINT NOT NULL COMMENT '关联数据源 ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '被授权用户 ID',
    MODIFY COLUMN granted_by BIGINT NOT NULL COMMENT '授权人用户 ID',
    MODIFY COLUMN granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '授权时间',
    MODIFY COLUMN expires_at DATETIME NULL COMMENT '授权过期时间，NULL 表示永不过期';

ALTER TABLE datasource_health_check COMMENT = '数据源健康检查记录表';

ALTER TABLE datasource_health_check
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN datasource_id BIGINT NULL COMMENT '关联数据源 ID，临时测试可为空',
    MODIFY COLUMN check_type VARCHAR(20) NOT NULL COMMENT '检查类型：MANUAL/SCHEDULED',
    MODIFY COLUMN success TINYINT NOT NULL COMMENT '检查结果：1=成功，0=失败',
    MODIFY COLUMN response_time_ms INT NULL COMMENT '响应耗时，单位毫秒',
    MODIFY COLUMN server_version VARCHAR(100) NULL COMMENT '数据库服务端版本',
    MODIFY COLUMN error_message VARCHAR(1000) NULL COMMENT '失败原因',
    MODIFY COLUMN checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '检查时间';
