ALTER TABLE sys_department COMMENT = '系统部门表';

ALTER TABLE sys_department
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN parent_id BIGINT NULL COMMENT '上级部门 ID，NULL 表示顶级部门',
    MODIFY COLUMN dept_name VARCHAR(50) NOT NULL COMMENT '部门名称',
    MODIFY COLUMN dept_code VARCHAR(50) NOT NULL COMMENT '部门编码',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '排序号，数值越小越靠前',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '部门状态：1=启用，0=禁用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE sys_role COMMENT = '系统角色表';

ALTER TABLE sys_role
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN role_code VARCHAR(50) NOT NULL COMMENT '角色编码',
    MODIFY COLUMN role_name VARCHAR(50) NOT NULL COMMENT '角色名称',
    MODIFY COLUMN description VARCHAR(200) NULL COMMENT '角色描述',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '角色状态：1=启用，0=禁用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE sys_user COMMENT = '系统用户表';

ALTER TABLE sys_user
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN username VARCHAR(50) NOT NULL COMMENT '登录用户名',
    MODIFY COLUMN password_hash VARCHAR(100) NOT NULL COMMENT 'BCrypt 加密后的登录密码',
    MODIFY COLUMN password_changed TINYINT NOT NULL DEFAULT 0 COMMENT '是否已修改初始密码：1=已修改，0=未修改',
    MODIFY COLUMN real_name VARCHAR(50) NOT NULL COMMENT '用户真实姓名',
    MODIFY COLUMN email VARCHAR(100) NULL COMMENT '邮箱地址',
    MODIFY COLUMN phone VARCHAR(20) NULL COMMENT '手机号码',
    MODIFY COLUMN department_id BIGINT NULL COMMENT '所属部门 ID',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '用户状态：1=启用，0=禁用',
    MODIFY COLUMN last_login_at DATETIME NULL COMMENT '最后登录时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：1=已删除，0=未删除';

ALTER TABLE sys_permission COMMENT = '系统权限表';

ALTER TABLE sys_permission
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN permission_code VARCHAR(100) NOT NULL COMMENT '权限编码',
    MODIFY COLUMN permission_name VARCHAR(100) NOT NULL COMMENT '权限名称',
    MODIFY COLUMN module VARCHAR(50) NOT NULL COMMENT '所属模块',
    MODIFY COLUMN description VARCHAR(200) NULL COMMENT '权限描述';

ALTER TABLE sys_user_role COMMENT = '用户角色关联表';

ALTER TABLE sys_user_role
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户 ID',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色 ID';

ALTER TABLE sys_role_permission COMMENT = '角色权限关联表';

ALTER TABLE sys_role_permission
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色 ID',
    MODIFY COLUMN permission_id BIGINT NOT NULL COMMENT '权限 ID';
