package com.dataocean.module.permission.s1.mapper;

import com.dataocean.module.permission.s1.IamS1Constants;
import com.dataocean.module.permission.s1.entity.IamS1DataGrant;
import com.dataocean.module.permission.s1.entity.IamS1PermissionRevision;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;

import javax.sql.DataSource;
import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/** 真实 H2 Mapper SQL 与事务回滚测试；不连接真实 MySQL。 */
@SpringBootTest
@ActiveProfiles("test")
@Sql(statements = {
        "DROP TABLE IF EXISTS iam_s1_data_grant_column",
        "DROP TABLE IF EXISTS iam_s1_row_condition",
        "DROP TABLE IF EXISTS iam_s1_field_protection",
        "DROP TABLE IF EXISTS iam_s1_data_grant",
        "DROP TABLE IF EXISTS iam_s1_permission_revision",
        "CREATE TABLE iam_s1_permission_revision (revision_no BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, target_type VARCHAR(50), target_id BIGINT, change_type VARCHAR(50), operator_id BIGINT, reason VARCHAR(500), created_at TIMESTAMP)",
        "CREATE TABLE iam_s1_data_grant (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, protocol_version VARCHAR(50), subject_type VARCHAR(20), subject_id BIGINT, department_scope VARCHAR(30), datasource_id BIGINT, resource_scope VARCHAR(20), metadata_snapshot_id BIGINT, table_name VARCHAR(200), effect VARCHAR(10), grant_source VARCHAR(30), source_reference_id BIGINT, valid_from TIMESTAMP, valid_until TIMESTAMP, status VARCHAR(20), revision_no BIGINT, created_by BIGINT, updated_by BIGINT, created_at TIMESTAMP, updated_at TIMESTAMP)",
        "CREATE TABLE iam_s1_data_grant_column (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, grant_id BIGINT, metadata_snapshot_id BIGINT, column_meta_id BIGINT, table_name VARCHAR(200), column_name VARCHAR(200), created_at TIMESTAMP)",
        "CREATE TABLE iam_s1_row_condition (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, grant_id BIGINT, metadata_snapshot_id BIGINT, table_name VARCHAR(200), match_type VARCHAR(10), sequence_no INT, column_meta_id BIGINT, column_name VARCHAR(200), operator_code VARCHAR(20), value_type VARCHAR(30), structured_value_json VARCHAR(4000), parameter_reference VARCHAR(100), created_at TIMESTAMP)",
        "CREATE TABLE iam_s1_field_protection (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, protocol_version VARCHAR(50), datasource_id BIGINT, metadata_snapshot_id BIGINT, table_name VARCHAR(200), column_meta_id BIGINT, column_name VARCHAR(200), protection_level VARCHAR(20), mask_policy VARCHAR(100), status VARCHAR(20), revision_no BIGINT, created_by BIGINT, updated_by BIGINT, created_at TIMESTAMP, updated_at TIMESTAMP)"
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
@Sql(statements = {
        "DROP TABLE IF EXISTS iam_s1_data_grant_column",
        "DROP TABLE IF EXISTS iam_s1_row_condition",
        "DROP TABLE IF EXISTS iam_s1_field_protection",
        "DROP TABLE IF EXISTS iam_s1_data_grant",
        "DROP TABLE IF EXISTS iam_s1_permission_revision"
}, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
class IamS1DataAuthorizationMapperTest {

    @Autowired
    private DataSource dataSource;
    @Autowired
    private IamS1DataGrantMapper grantMapper;
    @Autowired
    private IamS1PermissionRevisionMapper revisionMapper;

    @Test
    void mapperReadsOnlyActiveS1GrantRows() {
        IamS1DataGrant active = grant("orders", IamS1Constants.EFFECT_ALLOW);
        grantMapper.insert(active);
        IamS1DataGrant revoked = grant("customers", IamS1Constants.EFFECT_ALLOW);
        revoked.setStatus(IamS1Constants.DATA_GRANT_STATUS_REVOKED);
        grantMapper.insert(revoked);

        List<IamS1DataGrant> rows = grantMapper.selectActiveByDatasource(IamS1Constants.PROTOCOL_VERSION, 1L);
        assertThat(rows).extracting(IamS1DataGrant::getTableName).containsExactly("orders");
    }

    @Test
    void databaseRollbackRemovesGrantAndRevisionTogether() {
        TransactionTemplate transactionTemplate = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        transactionTemplate.executeWithoutResult(status -> {
            grantMapper.insert(grant("orders", IamS1Constants.EFFECT_ALLOW));
            IamS1PermissionRevision revision = new IamS1PermissionRevision();
            revision.setTargetType("DATA_GRANT");
            revision.setChangeType("CREATE");
            revision.setOperatorId(1L);
            revisionMapper.insert(revision);
            status.setRollbackOnly();
        });
        assertThat(grantMapper.selectActiveByDatasource(IamS1Constants.PROTOCOL_VERSION, 1L)).isEmpty();
        assertThat(revisionMapper.selectCurrentRevision()).isNull();
    }

    private IamS1DataGrant grant(String tableName, String effect) {
        IamS1DataGrant grant = new IamS1DataGrant();
        grant.setProtocolVersion(IamS1Constants.PROTOCOL_VERSION);
        grant.setSubjectType(IamS1Constants.SUBJECT_USER);
        grant.setSubjectId(7L);
        grant.setDatasourceId(1L);
        grant.setResourceScope(IamS1Constants.RESOURCE_SCOPE_TABLE);
        grant.setMetadataSnapshotId(88L);
        grant.setTableName(tableName);
        grant.setEffect(effect);
        grant.setGrantSource(IamS1Constants.GRANT_SOURCE_MANUAL);
        grant.setValidFrom(LocalDateTime.of(2026, 9, 17, 9, 0));
        grant.setStatus(IamS1Constants.DATA_GRANT_STATUS_ACTIVE);
        grant.setRevisionNo(1L);
        grant.setCreatedBy(1L);
        return grant;
    }
}
